### ISSUE TITLE
chamfer.o No such file or directory

### ISSUE THREAD

**Issue by mingmou123** [hzxie/GRNet#18]
hello, when I run the chamfer_dist,  I met the problem "GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o: no such file or directory" , how can I solve this problem?

**Comment by hzxie** [comment]
I can't reproduce this error.
Please provide the full logs and your system environment (including OS, Python Version, PyTorch Version).

**Comment by mingmou123** [comment]
> lease provide the full logs and your system environment (including OS, Python Version, PyTorch Version).

ubuntu 18.04 python3.7 pytorch 1.5.0
GRNet) :~/code/GRNet/extensions/chamfer_dist$ python setup.py install --user
running install
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer' extension
Emitting ninja build file /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /home/muxinyue/anaconda3/envs/GRNet/compiler_compat -L/home/muxinyue/anaconda3/envs/GRNet/lib -Wl,-rpath=/home/muxinyue/anaconda3/envs/GRNet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer_cuda.o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -L/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/lib -L:/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/chamfer.cpython-37m-x86_64-linux-gnu.so
g++: error: /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o: 没有那个文件或目录
error: command 'g++' failed with exit status 1

can you tell me how to solve it?

**Comment by mingmou123** [comment]
@hzxie 
ubuntu 18.04 python3.7 pytorch 1.5.0
GRNet) :~/code/GRNet/extensions/chamfer_dist$ python setup.py install --user
running install
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer' extension
Emitting ninja build file /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /home/muxinyue/anaconda3/envs/GRNet/compiler_compat -L/home/muxinyue/anaconda3/envs/GRNet/lib -Wl,-rpath=/home/muxinyue/anaconda3/envs/GRNet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer_cuda.o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -L/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/lib -L:/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/chamfer.cpython-37m-x86_64-linux-gnu.so
g++: error: /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o: 没有那个文件或目录
error: command 'g++' failed with exit status 1

can you tell me how to solve it?

**Comment by mingmou123** [comment]
ubuntu 18.04 python3.7 pytorch 1.5.0

python setup.py install --user
running install
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer' extension
Emitting ninja build file /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda-10.1/bin/nvcc -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/TH -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/muxinyue/anaconda3/envs/GRNet/include/python3.7m -c -c /home/muxinyue/code/GRNet/extensions/chamfer_dist/chamfer.cu -o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o 
:/usr/local/cuda-10.1/bin/nvcc -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/TH -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/muxinyue/anaconda3/envs/GRNet/include/python3.7m -c -c /home/muxinyue/code/GRNet/extensions/chamfer_dist/chamfer.cu -o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
**/bin/sh: 1: :/usr/local/cuda-10.1/bin/nvcc: not found
ninja: build stopped: subcommand failed.**
Traceback (most recent call last):
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

can you tell me how to solve it? I confirm that the nvcc path has all ready been added into the path.

**Comment by mingmou123** [comment]
ubuntu 18.04 python3.7 pytorch 1.5.0

python setup.py install --user
running install
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer' extension
Emitting ninja build file /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda-10.1/bin/nvcc -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/TH -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/muxinyue/anaconda3/envs/GRNet/include/python3.7m -c -c /home/muxinyue/code/GRNet/extensions/chamfer_dist/chamfer.cu -o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o
:/usr/local/cuda-10.1/bin/nvcc -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/TH -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/muxinyue/anaconda3/envs/GRNet/include/python3.7m -c -c /home/muxinyue/code/GRNet/extensions/chamfer_dist/chamfer.cu -o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/bin/sh: 1: :/usr/local/cuda-10.1/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
check=True)
File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

if I fix the  '['ninja', '-v']' with  '['ninja', '--version']'  there appears another error: GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o: 没有那个文件或目录

can you tell me how to solve it? I confirm that the nvcc path has all ready been added into the path.

**Comment by mingmou123** [comment]
@hzxie 
ubuntu 18.04 python3.7 pytorch 1.5.0

python setup.py install --user

Compiling objects...

**FAILED: /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o**
:/usr/local/cuda-10.1/bin/nvcc -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/TH -I/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/muxinyue/anaconda3/envs/GRNet/include/python3.7m -c -c /home/muxinyue/code/GRNet/extensions/chamfer_dist/chamfer.cu -o /home/muxinyue/code/GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
**/bin/sh: 1: :/usr/local/cuda-10.1/bin/nvcc: not found
ninja: build stopped: subcommand failed.**
Traceback (most recent call last):
File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
check=True)
File "/home/muxinyue/anaconda3/envs/GRNet/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

if I fix the '['ninja', '-v']' with '['ninja', '--version']' there was appeared another error: GRNet/extensions/chamfer_dist/build/temp.linux-x86_64-3.7/chamfer.o: 没有那个文件或目录

can you tell me how to solve it? I confirm that the nvcc path has all ready been added into the path.

**Comment by hzxie** [comment]
The log said "/bin/sh: 1: :/usr/local/cuda-10.1/bin/nvcc: not found"

**Comment by mingmou123** [comment]
@hzxie 
but I find nvcc in this folder, and I also add the path, what's wrong? Thanks.

**Comment by hzxie** [comment]
Please double check the PATH variable.
