### ISSUE TITLE
Questions about the version of some packages

### ISSUE THREAD

**Issue by sakjdas** [hzxie/GRNet#57]
Hello, can you give the version of all the packages since I met a lot problems during doing python setup.py. thanks a lot

**Comment by hzxie** [comment]
Could you give me the error log?

**Comment by sakjdas** [comment]
Now I have solved most of the error messages, and the setup.py command worked for champfer_dist, cubic_feature_sampling, gridding_loss as shown below.

running install
C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing chamfer.egg-info\PKG-INFO
writing dependency_links to chamfer.egg-info\dependency_links.txt
writing top-level names to chamfer.egg-info\top_level.txt
reading manifest file 'chamfer.egg-info\SOURCES.txt'
writing manifest file 'chamfer.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
creating build\bdist.win-amd64\egg
copying build\lib.win-amd64-3.7\chamfer.cp37-win_amd64.pyd -> build\bdist.win-amd64\egg
creating stub loader for chamfer.cp37-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\chamfer.py to chamfer.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying chamfer.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying chamfer.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying chamfer.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying chamfer.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.chamfer.cpython-37: module references __file__
creating 'dist\chamfer-2.0.0-py3.7-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing chamfer-2.0.0-py3.7-win-amd64.egg
removing 'c:\users\86157\appdata\roaming\python\python37\site-packages\chamfer-2.0.0-py3.7-win-amd64.egg' (and everything under it)
creating c:\users\86157\appdata\roaming\python\python37\site-packages\chamfer-2.0.0-py3.7-win-amd64.egg
Extracting chamfer-2.0.0-py3.7-win-amd64.egg to c:\users\86157\appdata\roaming\python\python37\site-packages
chamfer 2.0.0 is already the active version in easy-install.pth

Installed c:\users\86157\appdata\roaming\python\python37\site-packages\chamfer-2.0.0-py3.7-win-amd64.egg
Processing dependencies for chamfer==2.0.0
Finished processing dependencies for chamfer==2.0.0


but the third one, gridding, can't pass the installation and shows the error messsage below.

C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing gridding.egg-info\PKG-INFO
writing dependency_links to gridding.egg-info\dependency_links.txt
writing top-level names to gridding.egg-info\top_level.txt
reading manifest file 'gridding.egg-info\SOURCES.txt'
writing manifest file 'gridding.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'gridding' extension
Emitting ninja build file C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\TH -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\Users\86157\anaconda3\envs\test10\include -IC:\Users\86157\anaconda3\envs\test10\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\gridding_reverse.cu -o C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\build\temp.win-amd64-3.7\Release\gridding_reverse.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=gridding -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
FAILED: C:/Users/86157/Desktop/TUM/Programming/GRNet/extensions/gridding/build/temp.win-amd64-3.7/Release/gridding_reverse.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\TH -IC:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\Users\86157\anaconda3\envs\test10\include -IC:\Users\86157\anaconda3\envs\test10\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\gridding_reverse.cu -o C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\build\temp.win-amd64-3.7\Release\gridding_reverse.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=gridding -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
C:\Users\86157\Desktop\TUM\Programming\GRNet\extensions\gridding\gridding_reverse.cu(9): fatal error C1083: 无法打开包括文件: “bits/stdc++.h”: No such file or directory
gridding_reverse.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\Users\86157\anaconda3\envs\test10\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\86157\anaconda3\envs\test10\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\86157\anaconda3\envs\test10\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

can you give me some hints or suggestions to solve it.

Best Regards

**Comment by sakjdas** [comment]
Thanks a lot, I have solved the issue.

**Comment by ggcchh1a** [comment]
how did you solve the issue

**Comment by sakjdas** [comment]
stdc++.h  is basically a header file that also includes every standard library and STL include file.  I download a  stdc++.h file (you can search it on google) and put it with other .h files together under same folder(where other .h files locate) in your path. That is what I did and everthing works fine as expected.
