### ISSUE TITLE
I encountered a strange problem when using KITTI for python3 runner. py -- inference -- weights=/path/to/retrained/model. pth

### ISSUE THREAD

**Issue by tsyyyds** [hzxie/GRNet#68]
Thank you for your excellent work, but I encountered a problem during the inference

INFO - 2024-07-04 21:12:49,351 - data_loaders - Collecting files of Taxonomy [ID=kitti-car, Name=Car]
INFO - 2024-07-04 21:12:49,365 - data_loaders - Complete collecting files of the dataset. Total files: 2401                                          
INFO - 2024-07-04 21:12:54,912 - inference - Recovering from GRNet-KITTI.pth ...
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/resource_sharer.py", line 138, in _serve
    with self._listener.accept() as conn:
  File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/connection.py", line 465, in accept
Segmentation fault (core dumped)
    deliver_challenge(c, self._authkey)
(GRNet) user1@user-SYS-4029GP-TRT:~/devHDD/GRNet$   File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/connection.py", line 740, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/user1/anaconda3/envs/GRNet/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by hzxie** [comment]
Please refer to the discussion in this [StackOverflow](https://stackoverflow.com/questions/47762973/python-pytorch-multiprocessing-throwing-errors-connection-reset-by-peer-and-f) thread.
I don't think this issue is related to our project.
